const storeSimple = {
    musicList: [
        {
            title: 'Universe',
            artist: '',
            cover: 'https://vmusic.ir/wp-content/uploads/2024/08/Jurrivh-Universe-2024.jpg',
            audio: 'https://dc.vmusic.ir/2024/08/Jurrivh - Universe (2024)/128k/01) Jurrivh - Universe.mp3',
            genre: 'relax',
        },
        {
            title: 'Øneheart',
            artist: '',
            cover: 'https://vmusic.ir/wp-content/uploads/2023/05/Oneheart-searching-for-you-2023.jpg',
            audio: 'https://db.vmusic.ir/2023/05/Øneheart - searching for you (2023)/128k/Øneheart - searching for you.mp3',
            genre: 'relax',

        },
        {
            title: 'You can get lost among the good old movies',
            artist: '',
            cover: 'https://vmusic.ir/wp-content/uploads/2024/08/Konstantin-Tyufyakin-Unnamed-2024.jpg',
            audio: 'https://dc.vmusic.ir/2024/07/Konstantin Tyufyakin - Unnamed (2024)/128k/01) Konstantin Tyufyakin - You can get lost among the good old movies.mp3',
            genre: 'relax',

        },
        {
            title: 'Evolution',
            artist: 'Interplay Records',
            cover: 'https://vmusic.ir/wp-content/uploads/2024/07/Interplay-Records-Interplay-Radio-Episode-513-2024.jpg',
            audio: 'https://dc.vmusic.ir/2024/07/Interplay Records - Interplay Radio Episode 513 (2024)/128k/03) Interplay Records - Evolution (Interplay 51).mp3',
            genre: 'electronic trance',
        },
        {
            title: 'Atlantis',
            artist: 'Interplay Records',
            cover: 'https://vmusic.ir/wp-content/uploads/2024/07/Interplay-Records-Interplay-Radio-Episode-513-2024.jpg',
            audio: 'https://dc.vmusic.ir/2024/07/Interplay Records - Interplay Radio Episode 513 (2024)/128k/04) Interplay Records - Atlantis (Interplay 513).mp3',
            genre: 'electronic trance',
        },
        {
            title: 'Serotonin',
            artist: 'Interplay Records',
            cover: 'https://vmusic.ir/wp-content/uploads/2024/07/Interplay-Records-Interplay-Radio-Episode-513-2024.jpg',
            audio: 'https://dc.vmusic.ir/2024/07/Interplay Records - Interplay Radio Episode 513 (2024)/128k/17) Interplay Records - Serotonin (Interplay 513).mp3',
            genre: 'electronic trance',
        },
        {
            title: 'Second Sunrise',
            artist: 'Global DJ Broadcast Weekly Drive 31',
            cover: 'https://vmusic.ir/wp-content/uploads/2024/08/Markus-Schulz-Global-DJ-Broadcast-Weekly-Drive-31-2024.jpg',
            audio: 'https://dc.vmusic.ir/2024/07/Markus Schulz - Global DJ Broadcast Weekly Drive 31 (2024)/128k/01) Daxson - Second Sunrise (GDJB Weekly Drive 31).mp3',
            genre: 'electronic trance',
        },
        {
            title: 'Hagelslag ',
            artist: 'Global DJ Broadcast Weekly Drive 31',
            cover: 'https://vmusic.ir/wp-content/uploads/2024/08/Markus-Schulz-Global-DJ-Broadcast-Weekly-Drive-31-2024.jpg',
            audio: 'https://dc.vmusic.ir/2024/07/Markus Schulz - Global DJ Broadcast Weekly Drive 31 (2024)/128k/02) ReOrder, First Effect - Hagelslag (GDJB Weekly Drive 31).mp3',
            genre: 'electronic trance',
        },
        {
            title: 'I Do It For You (Everything I Do)',
            artist: 'Bryan Adams',
            cover: 'https://ts2.tarafdari.com/contents/user6984/content-sound/bryan_adams-everything_i_do_i_do_it_for_you_s_4.jpg',
            audio: 'https://ts2.tarafdari.com/contents/user6984/content-sound/36.bryan_adams_-_everything_i_do_i_do_it_for_you.mp3',
            genre: 'pop rock',
        },
        {
            title: 'Atlantis',
            artist: 'Tycoos',
            cover: 'https://vmusic.ir/wp-content/uploads/2024/07/Tycoos-Future-Horizons-441-2024.jpg',
            audio: 'https://dc.vmusic.ir/2024/07/Tycoos - Future Horizons 441 (2024)/128k/03) Tycoos - Atlantis (Future Horizons 441).mp3',
            genre: 'electronic trance',
        },
        {
            title: 'Doost Daram Zendegi ro',
            artist: 'Sirvan',
            cover: 'https://upmusics.com/wp-content/uploads/2017/07/Sirvan-Khosravi-Doost-Daram-Zendegiro.jpg',
            audio: 'https://dls.music-fa.com/tagdl/downloads/Sirvan%20Khosravi%20-%20Doost%20Daram%20Zendegiro%20(128).mp3',
            genre: 'pop',
        },
        {
            title: 'Tanha Nazar',
            artist: 'Sirvan',
            cover: 'https://www.ganja2music.com/Image/Post/7.2019/Sirvan%20Khosravi%20-%20Tanha%20Nazar.jpg',
            audio: 'https://irsv.upmusics.com/Downloads/Musics/Sirvan%20Khosravi%20%7C%20Tanha%20Nazar%20(320).mp3',
            genre: 'pop electronic',
        },
        {
            title: 'No Step On Wing',
            artist: 'Nils Frahm',
            cover: 'https://vmusic.ir/wp-content/uploads/2020/03/Nils-Frahm-Empty-2020.jpg',
            audio: 'https://dl.vmusic.ir//2020/03/Nils Frahm - Empty (2020)/128k/03) Nils Frahm - No Step On Wing - 2020.mp3',
            genre: 'relax piano ambient',
        },
        {
            title: 'What I’ve Done',
            artist: 'LinkinPark',
            cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ-yAY8vyC_ADH0A3tkOFqiDUBk5dVK3yUaRg&s',
            audio: 'https://ememay.ir/wp-content/uploads/2024/04/Linkin-Park-What-Ive-Done.mp3',
            genre: 'rock metal',
        },
        {
            title: 'Abri',
            artist: 'Farvardin',
            cover: 'https://i1.sndcdn.com/artworks-JPQ7KL2kKbzxt59y-rDIPiw-t500x500.jpg',
            audio: 'https://cf-media.sndcdn.com/sTEmf0J8H8TO.128.mp3?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLW1lZGlhLnNuZGNkbi5jb20vc1RFbWYwSjhIOFRPLjEyOC5tcDMqIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNzI0NTQxNDU1fX19XX0_&Signature=InCjE8zBPpbOat~UieLY1FxrMJG6BIeUF1691S7UVrL9bA2N4FtWrgIQeq~jKJkQJlyG-YP4gmCzy4Ovm31S57y514Xh4ChYOGNWTVyeZWU8b5tX8sYDOOiS03ESuITAkb4XA5rF73vkkBe9omV3puOPm8nR~j2jk0R0BFRCPu90bFV5-vfo7nOoZ4ZeVGkqeafqvjXPQmnzdqn-IGwtlcSL7eFKvE~U5Rs4ERSqSNmO4AWvQhnbAVvKjLV1IdJsn5o0RDRL6KyKLIfZgYjc6IGqwjBw33zbNGT-uHFiaFNoyloypl10lUHUgQ-hATInAtdhwZqdcaRsjCmFhRskPA__&Key-Pair-Id=APKAI6TU7MMXM5DG6EPQ',
            genre: 'pop',
        },
        {
            title: 'Buck dich',
            artist: 'Rammstein',
            cover: 'https://i.ytimg.com/vi/veZaHimbtaQ/sddefault.jpg',
            audio: 'https://ememay.ir/wp-content/uploads/2024/03/Rammstein-Buck-dich.mp3',
            genre: 'rock metal',
        },
        {
            title: 'In the End',
            artist: 'LinkinPark',
            cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQYwGBA3Zch4vi2eD2aEH_Cq136VyvxSQHHDA&s',
            audio: 'https://ememay.ir/wp-content/uploads/2024/04/Linkin-Park-In-the-End.mp3',
            genre: 'rock',
        },
        {
            title: 'Khanom Gol',
            artist: 'Ebi',
            cover: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcThIfO_ydjF7ly2z_kVJOZt5ssTf1hODhSRuP-AS8eJGnTpOv5rFzP7ZpFzmIzrvwoXBbc&usqp=CAU',
            audio: 'https://dl.shabamusic.com/Music/1402/09/19/Ebi - Khanom Gol (128).mp3',
            genre: 'nostalgy',
        },
        {
            title: 'Zombies',
            artist: 'The Cranberries',
            cover: 'https://m.media-amazon.com/images/M/MV5BZWQ1ODZjM2YtYmU2Yy00NTNjLTg3MzYtZmU1MzgyOWYyYzg5XkEyXkFqcGdeQXVyNDE4OTY5NzI@._V1_FMjpg_UX1000_.jpg',
            audio: 'https://ememay.ir/wp-content/uploads/2023/12/Zombie-The-Cranberries.mp3',
            genre: 'rock',
        },
        {
            title: 'You',
            artist: 'Rostislav Khalikov',
            cover: 'https://vmusic.ir/wp-content/uploads/2024/07/Rostislav-Khalikov-Waiting-for-a-Miracle-2024.jpg',
            audio: 'https://dc.vmusic.ir/2024/07/Rostislav Khalikov - Waiting for a Miracle (2024)/128k/01) Rostislav Khalikov - You.mp3',
            genre: 'relax piano',
        },
        {
            title: 'Melody Box',
            artist: 'Rostislav Khalikov',
            cover: 'https://vmusic.ir/wp-content/uploads/2024/07/Rostislav-Khalikov-Waiting-for-a-Miracle-2024.jpg',
            audio: 'https://dc.vmusic.ir/2024/07/Rostislav Khalikov - Waiting for a Miracle (2024)/128k/02) Rostislav Khalikov - Melody Box.mp3',
            genre: 'relax piano',
        },
        {
            title: 'Awakening',
            artist: 'Rostislav Khalikov',
            cover: 'https://vmusic.ir/wp-content/uploads/2024/07/Rostislav-Khalikov-Waiting-for-a-Miracle-2024.jpg',
            audio: 'https://dc.vmusic.ir/2024/07/Rostislav Khalikov - Waiting for a Miracle (2024)/128k/03) Rostislav Khalikov - Awakening.mp3',
            genre: 'relax piano',
        },
        {
            title: 'Echo of the First Love',
            artist: 'Rostislav Khalikov',
            cover: 'https://vmusic.ir/wp-content/uploads/2024/07/Rostislav-Khalikov-Waiting-for-a-Miracle-2024.jpg',
            audio: 'https://dc.vmusic.ir/2024/07/Rostislav Khalikov - Waiting for a Miracle (2024)/128k/04) Rostislav Khalikov - Echo of the First Love.mp3',
            genre: 'relax piano',
        },
        {
            title: 'Memories',
            artist: 'Rostislav Khalikov',
            cover: 'https://vmusic.ir/wp-content/uploads/2024/07/Rostislav-Khalikov-Waiting-for-a-Miracle-2024.jpg',
            audio: 'https://dc.vmusic.ir/2024/07/Rostislav Khalikov - Waiting for a Miracle (2024)/128k/05) Rostislav Khalikov - Memories.mp3',
            genre: 'relax piano',
        },
        {
            title: 'Night Dream',
            artist: 'Rostislav Khalikov',
            cover: 'https://vmusic.ir/wp-content/uploads/2024/07/Rostislav-Khalikov-Waiting-for-a-Miracle-2024.jpg',
            audio: 'https://dc.vmusic.ir/2024/07/Rostislav Khalikov - Waiting for a Miracle (2024)/128k/07) Rostislav Khalikov - Night Dream.mp3',
            genre: 'relax piano',
        },
        {
            title: 'Good Night',
            artist: 'Rostislav Khalikov',
            cover: 'https://vmusic.ir/wp-content/uploads/2024/07/Rostislav-Khalikov-Waiting-for-a-Miracle-2024.jpg',
            audio: 'https://dc.vmusic.ir/2024/07/Rostislav Khalikov - Waiting for a Miracle (2024)/128k/10) Rostislav Khalikov - Good Night.mp3',
            genre: 'relax piano',
        },
        {
            title: 'Your Smile',
            artist: 'Rostislav Khalikov',
            cover: 'https://vmusic.ir/wp-content/uploads/2024/07/Rostislav-Khalikov-Waiting-for-a-Miracle-2024.jpg',
            audio: 'https://dc.vmusic.ir/2024/07/Rostislav Khalikov - Waiting for a Miracle (2024)/128k/16) Rostislav Khalikov - Your Smile.mp3',
            genre: 'relax piano',
        }, {
            title: 'Magical Woman',
            artist: 'Rostislav Khalikov',
            cover: 'https://vmusic.ir/wp-content/uploads/2024/07/Rostislav-Khalikov-Waiting-for-a-Miracle-2024.jpg',
            audio: 'https://dc.vmusic.ir/2024/07/Rostislav Khalikov - Waiting for a Miracle (2024)/128k/19) Rostislav Khalikov - Magical Woman.mp3',
            genre: 'relax piano',
        },
        {
            title: 'sahdana',
            artist: 'Ildio',
            cover: 'https://vmusic.ir/wp-content/uploads/2024/08/ildio-sahdana-2024.jpg',
            audio: 'https://dc.vmusic.ir/2024/08/ildio - sahdana (2024)/128k/01) ildio - sahdana.mp3',
            genre: 'relax piano',
        },
        {
            title: 'Surya namaskar',
            artist: 'Ildio',
            cover: 'https://vmusic.ir/wp-content/uploads/2024/08/ildio-sahdana-2024.jpg',
            audio: 'https://dc.vmusic.ir/2024/08/ildio - sahdana (2024)/128k/02) ildio - surya namaskar.mp3',
            genre: 'relax piano',
        },
        {
            title: 'Maste Cheshat',
            artist: 'Farvardin',
            cover: 'https://i1.sndcdn.com/artworks-hgLIhtAvtsVE-0-t500x500.jpg',
            audio: 'https://cf-media.sndcdn.com/024Z8rUxjRF0.128.mp3?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLW1lZGlhLnNuZGNkbi5jb20vMDI0WjhyVXhqUkYwLjEyOC5tcDMqIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNzI0NTQ1MDk2fX19XX0_&Signature=EbcwBFiCvopzqG0ZbfKshq5UxnDsB-wXjAi85UyNylJOKL9jjQGoaf~rq9NWzPJq9TIAuos-LNEcGWA97nE9a-Ihnzv0PRJzIyQ1jXX~~RB6lPkHZn0kYSTJhd63n-XhI8mCcJlyFCnLrlF6IfIbDwqfZGlcNP4abTWmj1R7N64-MwbwGcaJq0ticLwQfGuI05G6H~5dbfnl6aeXqgWhYOLGQaWHEHBIaTZq9b06J0CozmOfW6xucCN938Sb04YKU9Q8xuvfg5VfkG1gZrrTPW674X9cpm6HHxdrzZGtTgOLeqMvvKiKxVyf4q37WBNAcftrN~gUNl~o4MkC4LDnMQ__&Key-Pair-Id=APKAI6TU7MMXM5DG6EPQ',
            genre: 'pop electronic',
        },
        {
            title: 'Never Alone',
            artist: 'Carbon & Lampé',
            cover: 'https://i1.sndcdn.com/artworks-MEy6VBgvP1BMdtsR-PPz8jA-t500x500.jpg',
            audio: 'https://cf-media.sndcdn.com/a2geNGn3kFjU.128.mp3?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLW1lZGlhLnNuZGNkbi5jb20vYTJnZU5HbjNrRmpVLjEyOC5tcDMqIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNzI0NTQ1NDI5fX19XX0_&Signature=Ovq-Cfe9DwKhEaFLB2B3pTSFrcF6aWEZmJ46Ymrrj1VdKjuJ7d6771N03BigwOdLJxo~~6fLDeCDyPDIo4uGMUm0yDWNafLaMdTbbkI734BMq03Ntb7TFyMCbHwrVzCrzMyVg4QnSbIGnnBVcgtkOtMAT7hdwhQRXSv5WwetDFCe3dGRD8Q1aORhdfxmOBQCPCAbFgoidpC7LHKs0iaGlRoDjyc~TGXFoJpgLREJqJrBf1eg4kh7ozRbDJdmO7nXTZVSTOh~UKBvpo7ZN8rlsY1OjSQ9CnnQKecoYECR1mPfYV-qM3k-GPsoS-6C9e7~pCvsnGt3GSCPPKT1ePHpiA__&Key-Pair-Id=APKAI6TU7MMXM5DG6EPQ',
            genre: 'electronic techno',
        },
        // {
        //     title: 'All of my music is on Spotify',
        //     artist: 'Wind',
        //     cover: 'https://i1.sndcdn.com/artworks-000033182580-ja3l0t-t500x500.jpg',
        //     audio: 'https://cf-media.sndcdn.com/gfihOXhUVnpV.128.mp3?Policy=eyJTdGF0ZW1lbnQiOlt7IlJlc291cmNlIjoiKjovL2NmLW1lZGlhLnNuZGNkbi5jb20vZ2ZpaE9YaFVWbnBWLjEyOC5tcDMqIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNzI0NTQ1OTkyfX19XX0_&Signature=PIwhLXLr-DggbJJlF1X5JfnIZONkaxH2Z3pUudPk-a3b24IjPIALkJb0eiMrAIRLTLrC4agsWTRunK0akfAGG~FliCdq28KdIN6xA66DEBunZ2hslb06qmaka32VuRWa~Awm-vQtV5sqVG0LQ27AlWc9Gnm-FSdejUtUiGrZg~FyeI08Yde9loaMGG--8uJKRWwyVe4BovRTB~dxW5YzrNt5~m6Vgsebwt4u9qKC6Tw6MRz-fRzHAEndaa042yrjUsCAXFmxzPSUh7arvE2fbXt6A4Ri8HGIJJVNcPux6kHU2Gb5Dq7Ggb-cAgNfj4BNNAfrHRA4u44NMIc8tjntjg__&Key-Pair-Id=APKAI6TU7MMXM5DG6EPQ',
        //     genre: 'relax piano',
        // },
        {
            title: 'The Love',
            artist: 'Florews',
            cover: 'https://vmusic.ir/wp-content/uploads/2024/08/Florews-Cinematic-Piano-2024.jpg',
            audio: 'https://dc.vmusic.ir/2024/08/Florews - Cinematic Piano (2024)/128k/01) Florews - The Love.mp3',
            genre: 'relax piano',
        },
        {
            title: 'Tension to Relief',
            artist: '',
            cover: 'https://vmusic.ir/wp-content/uploads/2024/08/Various-Artists-Changes-Human-Stories-Factual-2024.jpg',
            audio: 'https://dc.vmusic.ir/2024/08/Various Artists - Changes - Human Stories & Factual (2024)/128k/01) Theo Vidgen - Tension to Relief.mp3',
            genre: 'relax piano',
        },
        {
            title: 'Struggle to Survival',
            artist: '',
            cover: 'https://vmusic.ir/wp-content/uploads/2024/08/Various-Artists-Changes-Human-Stories-Factual-2024.jpg',
            audio: 'https://dc.vmusic.ir/2024/08/Various Artists - Changes - Human Stories & Factual (2024)/128k/02) Isabella Catherine Lau - Struggle to Survival.mp3',
            genre: 'relax piano',
        },
        {
            title: 'Expectation to Arrival',
            artist: '',
            cover: 'https://vmusic.ir/wp-content/uploads/2024/08/Various-Artists-Changes-Human-Stories-Factual-2024.jpg',
            audio: 'https://dc.vmusic.ir/2024/08/Various Artists - Changes - Human Stories & Factual (2024)/128k/03) Angus Thomas Nicholson - Expectation to Arrival.mp3',
            genre: 'relax piano',
        },
        {
            title: 'Calm to Busy',
            artist: '',
            cover: 'https://vmusic.ir/wp-content/uploads/2024/08/Various-Artists-Changes-Human-Stories-Factual-2024.jpg',
            audio: 'https://dc.vmusic.ir/2024/08/Various Artists - Changes - Human Stories & Factual (2024)/128k/05) Chris Doney - Calm to Busy.mp3',
            genre: 'relax piano',
        },
        {
            title: 'Introspective to Optimistic',
            artist: '',
            cover: 'https://vmusic.ir/wp-content/uploads/2024/08/Various-Artists-Changes-Human-Stories-Factual-2024.jpg',
            audio: 'https://dc.vmusic.ir/2024/08/Various Artists - Changes - Human Stories & Factual (2024)/128k/07) Joshua Benjamin Pacey - Introspective to Optimistic.mp3',
            genre: 'relax piano',
        },
{
            title: 'Pacha Mama',
            artist: 'Galardo',
            cover: 'https://vmusic.ir/wp-content/uploads/2020/12/Galardo-Pacha-Mama-2020.jpg',
            audio: 'https://dl.vmusic.ir/2020/12/Galardo - Pacha Mama (2020)/128k/Galardo - Pacha Mama.mp3',
            genre: 'house electronic',
        },
    ],
    genres: [
        {
            genre: 'pop',
            icon: 'pop',
            text: 'Pop',
            active: true,
        },
        {
            genre: 'relax',
            icon: 'pop',
            text: 'Relax',
            active: true,

        },
        {
            genre: 'rock',
            icon: 'pop',
            text: 'Rock',
            active: true,

        },
        {
            genre: 'electronic',
            icon: 'pop',
            text: 'Electronic',
            active: true,
        },
    ],
}

export default storeSimple